### ISSUE TITLE
Add SPU sound support

### ISSUE THREAD

**Issue by francot514** [BluestormDNA/ProjectPSX#9]
Are you working anymore on this, can you add SPU sound support.

**Comment by BluestormDNA** [comment]
Yes, I'm still "working" on this. I got a job as a programmer and my time on this has lowered dramatically.

Certainly the volume of commits are not the same that once were.  But i think there has been some very good ones recently like 6c90a0a42d8f675fea14029541c1fd70451fb836 that made a lot of games to boot, or 3675227a034f5ab574123e5c08692f1140043ea7 that made Memory Cards working.
I'm currently working (from time to time) in implement resumable DMAs instead of handling them in just 1 cycle so i can let the cpu run in beetwen DMA blocks. Infact that part is done, the problem I need to fix is making also the MDEC work with that data. The current implementation thrashes the MDEC output. That would fix some games like Final Fantasy 9.

The SPU is not a trivial thing to add. First because i have absolutely no clue how sound works from a basic perspective and second because limitations on the current windowing system of ProjectPSX (a plain WinForm). Anyway I really have an itch for sound. And just this weekend I refactored [ProjectDMG ](https://github.com/BluestormDNA/ProjectDMG) (my GameBoy emu) from WinForms to OpenTK to see if i can learn how to handle and output sound on a more basic hardware like the GameBoy.
If i can make it work there for sure eventually ProjectPSX will have a SPU.

**Comment by Noplace** [comment]
Hi, if you are interested I copied your project a while back just for fun and attempted to add SPU but didn't finish, maybe this code could be useful to you, I would hope that I would find more time to contribute as I do have some audio/dsp experience and would love to contribute to a PSX emu
[BUS.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608733/BUS.cs.txt)
[SPU.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608735/SPU.cs.txt)
[DMA.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608736/DMA.cs.txt)
[DMA_Transfer.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608737/DMA_Transfer.cs.txt)

**Comment by francot514** [comment]
@BluestormDNA Ok good let me know when you get there.

@Noplace Can you share full project.

**Comment by Noplace** [comment]
@francot514 sure
[ProjectPSX-master.zip](https://github.com/BluestormDNA/ProjectPSX/files/4613569/ProjectPSX-master.zip)

**Comment by francot514** [comment]
@Noplace Not sure what you did but cdrom classnot working anymore and spu freezes it, can you upload project so we can try to make it work.

**Comment by BluestormDNA** [comment]
> 
> 
> Hi, if you are interested I copied your project a while back just for fun and attempted to add SPU but didn't finish, maybe this code could be useful to you, I would hope that I would find more time to contribute as I do have some audio/dsp experience and would love to contribute to a PSX emu
> [BUS.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608733/BUS.cs.txt)
> [SPU.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608735/SPU.cs.txt)
> [DMA.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608736/DMA.cs.txt)
> [DMA_Transfer.cs.txt](https://github.com/BluestormDNA/ProjectPSX/files/4608737/DMA_Transfer.cs.txt)

@Noplace that's amazing. Hope you find some time I would merge that in a heartbeat as long as it outputs something ;)

**Comment by BluestormDNA** [comment]
Closing this as ProjectPSX haves since some commits ago a somewhat working SPU.
